import SideBar from '../ui/SideBar'
import AdminHeader from '../ui/AdminHeader'
import { blocklistData } from './data/blockListData'
import Pagination from '../ui/Pagination'
import LLMList from './components/LLMList'
import { useState } from 'react'
import PromptTabs from './PromptTabs';
export default function StoryPrompts() {
    const [showAddForm, setShowAddForm] = useState(false)
    const [newWord, setNewWord] = useState('')
    const handleSave = () => {
        if (!newWord.trim()) return
        console.log('Save new blocked word:', newWord)
        setNewWord('')
        setShowAddForm(false)
    }
    return (
        <div className="flex items-start justify-center bg-[#F9F9F9]">
            <SideBar />
            <div className='w-full pb-4'>
                <AdminHeader />
                <div className='mt-6 px-6'>
                    <PromptTabs />
                </div>
                <div className='mt-6 px-6'>
                    <div className='flex items-center justify-between'>
                        <h1 className='text-[#1F2937] font-semibold text-[15.3px] leading-[28px]  text-xl'>AI LLM Blocklist</h1>
                        <div
                            className='flex items-center justify-center py-[8px] px-[16px] gap-2 cursor-pointer rounded-[6px]'
                            style={{ background: "linear-gradient(to right, #9458E8, #CA00E5)" }}
                            onClick={() => setShowAddForm(!showAddForm)}
                        >
                            <svg width="17" height="17" viewBox="0 0 17 17" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M3.677 8.5H13.0103" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                                <path d="M8.34375 3.83331V13.1666" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                            </svg>
                            <span className='text-[11.9px] leading-[20px] font-[400] text-[#FFFFFF] cursor-pointer  bg-gradient-to-r from-[#9458E8] via-[#A43EE7] to-[#CA00E5]'>Add Blocked Word</span>
                        </div>
                    </div>
                </div>
                {showAddForm && (
                    <div className='px-6 mt-4'>
                        <div className='bg-white p-6 rounded-[8px] border-[1px] border-[#E5E7EB]'>
                            <h3 className='font-[600] text-[14px] leading-[24px] text-[#1F2937]'>Add New LLM Blockword</h3>
                            <p className='mt-1 font-[400] text-[11.9px] leading-[20px] text-[#4B5563]'>Write the Word</p>
                            <input
                                type='text'
                                value={newWord}
                                onChange={(e) => setNewWord(e.target.value)}
                                placeholder='Enter blocked word'
                                className='w-full mt-2 px-3 py-2 border border-gray-300 rounded-lg text-[11.9px] leading-[20px] focus:outline-none focus:ring-2 focus:ring-purple-400'
                            />
                            <div className='flex items-center justify-end gap-4 mt-4'>
                                <button
                                    onClick={() => { setShowAddForm(false); setNewWord('') }}
                                    className='px-4 py-2 border border-[#9458E8] rounded-[6px] text-[#000000] text-[11.9px] leading-[20px]'
                                >
                                    Close
                                </button>
                                <button
                                    onClick={handleSave}
                                    className='px-4 py-2 rounded-[6px] text-white text-[11.9px] leading-[20px]'
                                    style={{ background: "linear-gradient(to right, #9458E8, #CA00E5)" }}
                                >
                                    Save Changes
                                </button>
                            </div>
                        </div>
                    </div>
                )}
                <div className='px-6 mt-6 '>
                    <div className='bg-white p-6 rounded-[8px] border-[1px] border-[#E5E7EB]'>
                        <p className='font-[400] text-[11.9px] leading-[20px] text-[#4B5563] inter-font'>
                            These words will be blocked from appearing in any content generated by the AI. The blocklist is applied to all story and song generations.
                        </p>
                    </div>
                </div>
                <div className='mt-6 px-6'>
                    <div className='bg-white rounded-[8px] shadow-md'>
                        <div>
                            <table className='w-full'>
                                <thead>
                                    <tr>
                                        <th className='font-semibold text-[14px] leading-[20px] text-[#333333] text-left p-[10px] border-b-[0.5px] border-[#EBEBEB]'>Word</th>
                                        <th className='font-semibold text-[14px] leading-[20px] text-[#333333] text-left p-[10px] border-b-[0.5px] border-[#EBEBEB]'>Date Added</th>
                                        <th className='font-semibold text-[14px] leading-[20px] text-[#333333] text-left p-[10px] border-b-[0.5px] border-[#EBEBEB]'>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {blocklistData.map((block, index) => (
                                        <tr key={index} className=" ">
                                            <LLMList block={block} />
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                        <Pagination />
                    </div>
                </div>
            </div>
        </div>
    )
}
