import SideBar from '../ui/SideBar'
import AdminHeader from '../ui/AdminHeader'
import SongIcon from '../svgs/SongIcon'
import LLMBlockListIcon from '../svgs/LLMBlockListIcon'
import StoryIcon from '../svgs/StoryIcon'
import { Link } from 'react-router-dom'
import { blocklistData } from './data/blockListData'
import Pagination from '../ui/Pagination'
import LLMList from './components/LLMList'

export default function StoryPrompts() {
    return (
        <div className="flex items-start justify-center bg-[#F9F9F9]">
            <SideBar />
            <div className='w-full pb-4'>
                <AdminHeader />
                <div className='mt-6    px-6'>
                    <div className='flex items-center justify-start gap-6 border-b-[1px] border-[#E5E7EB] '>
                        <div className='flex items-center justify-center gap-[10px] py-3 border-b-[2px] border-b-[#9458E8]'>
                            <StoryIcon color='' />
                            <Link to={`/dashboard/story-prompts`} className='font-[700] text-[11.9px] leading-[20px] text-[#9458E8] inter-font cursor-pointer'>Story</Link>
                        </div>
                        <div className='flex items-center justify-center gap-[10px] py-3'>
                            <SongIcon color='' />
                            <Link to={`/dashboard/audio-prompts`} className='font-[700] text-[11.9px] leading-[20px] text-[#6B7280] inter-font cursor-pointer'>Music</Link>
                        </div>
                        <div className='flex items-center justify-center gap-[10px] py-3'>
                            <LLMBlockListIcon />
                            <Link to={`/dashboard/llm-blocklist-prompts`} className='font-[700] text-[11.9px] leading-[20px] text-[#6B7280] inter-font cursor-pointer'>LLM Blocklist</Link>
                        </div>
                    </div>
                </div>
                <div className='mt-6 px-6'>
                    <div className='flex items-center justify-between'>
                        <h1 className='text-[#1F2937] text-[15.3px] leading-[28px] font-[600]'>AI LLM Blocklist</h1>
                        <div className='flex items-center justify-center py-[8px] px-[16px] gap-2 cursor-pointer rounded-[6px]' style={{background: "linear-gradient(to right, #9458E8, #CA00E5)"}}>
                            <svg width="17" height="17" viewBox="0 0 17 17" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M3.677 8.5H13.0103" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                                <path d="M8.34375 3.83331V13.1666" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                            </svg>
                            <button className='text-[11.9px] leading-[20px] font-[400] text-[#FFFFFF] cursor-pointer'>Add Blocked Word</button>
                        </div>
                    </div>
                </div>
                <div className='px-6 mt-6 '>
                    <div className='bg-white p-6 rounded-[8px] border-[1px] border-[#E5E7EB]'>
                        <p className='font-[400] text-[11.9px] leading-[20px] text-[#4B5563] inter-font'>These words will be blocked from appearing in any content generated by the AI. The blocklist is applied to all story and song generations.</p>
                    </div>
                </div>
                <div className='mt-6 px-6'>
                    <div className='bg-white rounded-[8px] shadow-md'>
                        <div>
                            <table className='w-full'>
                                <thead>
                                    <tr>
                                        <th className='font-semibold text-[14px] leading-[20px] text-[#333333] text-left p-[10px] border-b-[0.5px] border-[#EBEBEB]'>Word</th>
                                        <th className='font-semibold text-[14px] leading-[20px] text-[#333333] text-left p-[10px] border-b-[0.5px] border-[#EBEBEB]'>Date Added</th>
                                        <th className='font-semibold text-[14px] leading-[20px] text-[#333333] text-left p-[10px] border-b-[0.5px] border-[#EBEBEB]'>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {
                                        blocklistData.map((block, index) => (
                                            <tr key={index}>
                                                <LLMList  block={block} />
                                            </tr>
                                        ))
                                    }
                                </tbody>
                            </table>
                        </div>
                        <Pagination />
                    </div>
                </div>
            </div>
        </div>
    )
}
